name: ewas
channels:
  - r
  - bioconda/label/cf201901
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _r-mutex=1.0.1=anacondar_1
  - alsa-lib=1.2.3=h516909a_0
  - argparse=1.4.0=py27_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - backports_abc=0.5=py_1
  - bcftools=1.8=h4da6232_3
  - beagle=4.1_21Jan17.6cc.jar=1
  - bedtools=2.29.2=hc088bd4_0
  - binutils_impl_linux-64=2.34=h53a641e_7
  - binutils_linux-64=2.34=hc952b39_20
  - bioconductor-annotate=1.64.0=r36_0
  - bioconductor-annotationdbi=1.48.0=r36_0
  - bioconductor-annotationforge=1.28.0=r36_0
  - bioconductor-biobase=2.46.0=r36h516909a_0
  - bioconductor-biocgenerics=0.32.0=r36_0
  - bioconductor-category=2.52.0=r36_0
  - bioconductor-gem=1.12.0=r36_0
  - bioconductor-genefilter=1.68.0=r36hc99cbb1_0
  - bioconductor-go.db=3.10.0=r36_0
  - bioconductor-gostats=2.36.0=0
  - bioconductor-graph=1.64.0=r36h516909a_0
  - bioconductor-gseabase=1.48.0=r36_0
  - bioconductor-iranges=2.20.0=r36h516909a_0
  - bioconductor-rbgl=1.62.1=r36he1b5a44_0
  - bioconductor-rgraphviz=2.30.0=r36he1b5a44_0
  - bioconductor-s4vectors=0.24.0=r36h516909a_0
  - bwidget=1.9.14=0
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2019.11.28=py27h8c360ce_1
  - curl=7.71.1=he644dc0_5
  - cycler=0.10.0=py_2
  - datamash=1.1.0=0
  - docutils=0.16=py27h8c360ce_1
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.2=he06d7ca_0
  - fribidi=1.0.10=h516909a_0
  - functools32=3.2.3.2=py_3
  - futures=3.3.0=py27h8c360ce_1
  - gcc_impl_linux-64=7.5.0=hd420e75_6
  - gcc_linux-64=7.5.0=h09487f9_20
  - gettext=0.19.8.1=hc5be6a0_1002
  - gfortran_impl_linux-64=7.5.0=hdf63c60_6
  - gfortran_linux-64=7.5.0=h09487f9_20
  - giflib=5.2.1=h516909a_2
  - glib=2.65.0=h6f030ca_0
  - graphite2=1.3.13=he1b5a44_1001
  - gsl=2.6=h294904e_0
  - gxx_impl_linux-64=7.5.0=hdf63c60_6
  - gxx_linux-64=7.5.0=h09487f9_20
  - harfbuzz=2.4.0=h9f30f68_3
  - icu=64.2=he1b5a44_1
  - java-jdk=7.0.91=1
  - jpeg=9d=h516909a_0
  - kiwisolver=1.1.0=py27h9e3301b_1
  - krb5=1.17.1=hfafb76e_2
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.34=h53a641e_7
  - libblas=3.8.0=11_openblas
  - libcblas=3.8.0=11_openblas
  - libcurl=7.71.1=hcdd3856_5
  - libdeflate=1.6=h516909a_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h24d8f2e_16
  - libgfortran-ng=7.5.0=hdf63c60_16
  - libgomp=9.3.0=h24d8f2e_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.8.0=11_openblas
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libopenblas=0.3.6=h6e990d7_6
  - libpng=1.6.37=hed695b0_2
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=hdf63c60_16
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.9.2=he1b5a44_3
  - make=4.3=h516909a_0
  - matplotlib-base=2.2.5=py27h250f245_1
  - moreutils=0.5.7=1
  - ncurses=6.2=he1b5a44_1
  - numpy=1.16.5=py27h95a1406_0
  - olefile=0.46=py_0
  - openblas=0.3.6=h6e990d7_6
  - openjdk=11.0.8=hacce0ff_0
  - openssl=1.1.1g=h516909a_1
  - pango=1.42.4=h7062337_4
  - parallel=20200122=0
  - pcre=8.44=he1b5a44_0
  - perl=5.26.2=h516909a_1006
  - perl-vcftools-vcf=0.1.16=pl526_2
  - pillow=6.2.1=py27hd70f55b_1
  - pip=20.1.1=pyh9f0ad1d_0
  - pixman=0.38.0=h516909a_1003
  - plink=1.90b6.12=heea4ae3_1
  - pthread-stubs=0.4=h14c3975_1001
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=2.7.15=h5a48372_1011_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=2.7=1_cp27mu
  - pytz=2020.1=pyh9f0ad1d_0
  - r=3.6=r36_1004
  - r-argparser=0.6=r36_1
  - r-askpass=1.1=r36hcdcec82_2
  - r-assertthat=0.2.1=r36h6115d3f_2
  - r-backports=1.1.9=r36hcdcec82_0
  - r-base=3.6.3=h316533a_2
  - r-base64enc=0.1_3=r36hcdcec82_1004
  - r-bh=1.72.0_3=r36h6115d3f_1
  - r-bit=4.0.4=r36hcdcec82_0
  - r-bit64=4.0.5=r36hcdcec82_0
  - r-bitops=1.0_6=r36hcdcec82_1004
  - r-blob=1.2.1=r36h6115d3f_1
  - r-boot=1.3_25=r36h6115d3f_1
  - r-brew=1.0_6=r36h6115d3f_1003
  - r-callr=3.4.3=r36h6115d3f_1
  - r-class=7.3_17=r36hcdcec82_1
  - r-cli=2.0.2=r36h6115d3f_1
  - r-clipr=0.7.0=r36h6115d3f_1
  - r-cluster=2.1.0=r36h9bbef5b_3
  - r-codetools=0.2_16=r36h6115d3f_1002
  - r-colorspace=1.4_1=r36hcdcec82_2
  - r-commonmark=1.7=r36hcdcec82_1002
  - r-covr=3.5.0=r36h0357c0b_1
  - r-crayon=1.3.4=r36h6115d3f_1003
  - r-crosstalk=1.1.0.1=r36h6115d3f_1
  - r-curl=4.3=r36hcdcec82_1
  - r-data.table=1.12.8=r36hcdcec82_1
  - r-dbi=1.1.0=r36h6115d3f_1
  - r-desc=1.2.0=r36h6115d3f_1003
  - r-devtools=2.2.1=r36h6115d3f_0
  - r-digest=0.6.25=r36h0357c0b_2
  - r-dplyr=0.8.0.1=r36h29659fb_0
  - r-dt=0.15=r36h6115d3f_0
  - r-ellipsis=0.3.1=r36hcdcec82_0
  - r-evaluate=0.14=r36h6115d3f_2
  - r-fansi=0.4.1=r36hcdcec82_1
  - r-farver=2.0.3=r36h0357c0b_1
  - r-foreign=0.8_76=r36hcdcec82_1
  - r-fs=1.5.0=r36h0357c0b_0
  - r-ggplot2=3.1.1=r36h6115d3f_0
  - r-ggrepel=0.8.1=r36h0357c0b_1
  - r-gh=1.1.0=r36h6115d3f_1
  - r-git2r=0.27.1=r36h7253d3a_0
  - r-glue=1.4.2=r36hcdcec82_0
  - r-gtable=0.3.0=r36h6115d3f_3
  - r-hexbin=1.28.1=r36h9bbef5b_1
  - r-highr=0.8=r36h6115d3f_2
  - r-hms=0.5.3=r36h6115d3f_1
  - r-htmltools=0.5.0=r36h0357c0b_0
  - r-htmlwidgets=1.5.1=r36h6115d3f_1
  - r-httr=1.4.2=r36h6115d3f_0
  - r-ini=0.3.1=r36h6115d3f_1003
  - r-jsonlite=1.7.0=r36hcdcec82_0
  - r-kernsmooth=2.23_17=r36hfa343cc_1
  - r-knitr=1.29=r36h6115d3f_0
  - r-labeling=0.3=r36h6115d3f_1003
  - r-later=1.1.0.1=r36h0357c0b_0
  - r-lattice=0.20_41=r36hcdcec82_2
  - r-lazyeval=0.2.2=r36hcdcec82_2
  - r-lifecycle=0.2.0=r36h6115d3f_1
  - r-magrittr=1.5=r36h6115d3f_1003
  - r-markdown=1.1=r36hcdcec82_1
  - r-mass=7.3_52=r36hcdcec82_0
  - r-matrix=1.2_18=r36h7fa42b6_3
  - r-memoise=1.1.0=r36h6115d3f_1004
  - r-mgcv=1.8_33=r36h7fa42b6_0
  - r-mime=0.9=r36hcdcec82_1
  - r-munsell=0.5.0=r36h6115d3f_1003
  - r-nlme=3.1_149=r36h9bbef5b_0
  - r-nnet=7.3_14=r36hcdcec82_1
  - r-openssl=1.4.2=r36he5c4762_0
  - r-pillar=1.4.6=r36h6115d3f_0
  - r-pkgbuild=1.1.0=r36h6115d3f_0
  - r-pkgconfig=2.0.3=r36h6115d3f_1
  - r-pkgload=1.1.0=r36h0357c0b_0
  - r-plogr=0.2.0=r36h6115d3f_1003
  - r-plotly=4.9.2=r36h6115d3f_0
  - r-plyr=1.8.6=r36h0357c0b_1
  - r-praise=1.0.0=r36h6115d3f_1004
  - r-prettyunits=1.1.1=r36h6115d3f_1
  - r-processx=3.4.3=r36hcdcec82_0
  - r-promises=1.1.1=r36h0357c0b_0
  - r-ps=1.3.4=r36hcdcec82_0
  - r-purrr=0.3.4=r36hcdcec82_1
  - r-r6=2.4.1=r36h6115d3f_1
  - r-rcmdcheck=1.3.3=r36h6115d3f_3
  - r-rcolorbrewer=1.1_2=r36h6115d3f_0
  - r-rcpp=1.0.5=r36h0357c0b_0
  - r-rcurl=1.98_1.2=r36hcdcec82_1
  - r-readr=1.3.1=r36h0357c0b_1002
  - r-recommended=3.6=r36_1004
  - r-rematch2=2.1.2=r36h6115d3f_1
  - r-remotes=2.2.0=r36h6115d3f_0
  - r-reshape2=1.4.4=r36h0357c0b_1
  - r-rex=1.2.0=r36h6115d3f_1
  - r-rlang=0.4.7=r36hcdcec82_0
  - r-roxygen2=7.1.1=r36h0357c0b_0
  - r-rpart=4.1_15=r36hcdcec82_2
  - r-rprojroot=1.3_2=r36h6115d3f_1003
  - r-rsqlite=2.2.0=r36h0357c0b_2
  - r-rstudioapi=0.11=r36h6115d3f_1
  - r-rversions=2.0.2=r36h6115d3f_0
  - r-scales=1.1.1=r36h6115d3f_0
  - r-sessioninfo=1.1.1=r36h6115d3f_1002
  - r-spatial=7.3_12=r36hcdcec82_1
  - r-stringi=1.4.6=r36h0e574ca_2
  - r-stringr=1.4.0=r36h6115d3f_2
  - r-survival=3.2_3=r36hcdcec82_0
  - r-sys=3.4=r36hcdcec82_0
  - r-testthat=2.3.2=r36h0357c0b_1
  - r-tibble=3.0.3=r36hcdcec82_0
  - r-tidyr=0.8.3=r36h0357c0b_1
  - r-tidyselect=1.1.0=r36h6115d3f_0
  - r-usethis=1.6.1=r36h6115d3f_1
  - r-utf8=1.1.4=r36hcdcec82_1003
  - r-vctrs=0.3.4=r36hcdcec82_0
  - r-viridislite=0.3.0=r36h6115d3f_1003
  - r-whisker=0.4=r36h6115d3f_1
  - r-withr=2.2.0=r36h6115d3f_1
  - r-wordcloud2=0.2.1=r36h6115d3f_0
  - r-xfun=0.16=r36hcdcec82_0
  - r-xml=3.99_0.3=r36hcdcec82_1
  - r-xml2=1.3.2=r36h0357c0b_1
  - r-xopen=1.0.0=r36h6115d3f_1003
  - r-xtable=1.8_4=r36h6115d3f_3
  - r-yaml=2.2.1=r36hcdcec82_1
  - r-zeallot=0.1.0=r36h6115d3f_1002
  - r-zip=2.0.4=r36hcdcec82_0
  - readline=8.0=he28a2e2_2
  - sed=4.8=hbfbb72e_0
  - setuptools=44.0.0=py27_0
  - singledispatch=3.4.0.3=py27_1000
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=h4cf870e_0
  - statistics=1.0.3.5=py_1002
  - subprocess32=3.5.4=py27h516909a_0
  - tabix=0.2.6=ha92aebf_0
  - tk=8.6.10=hed695b0_0
  - tktable=2.10=h555a92e_3
  - tornado=5.1.1=py27h14c3975_1000
  - vcftools=0.1.16=he860b03_3
  - wheel=0.35.1=pyh9f0ad1d_0
  - wordcloud=1.6.0=py27h516909a_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxtst=1.2.3=h516909a_1002
  - xorg-recordproto=1.14.2=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1009
  - zstd=1.4.5=h6597ccf_2
