name: endor_gem
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - _r-mutex=1.0.1=anacondar_1
  - bcftools=1.9=h68d8f2e_9
  - bedtools=2.29.2=hc088bd4_0
  - binutils_impl_linux-64=2.33.1=h53a641e_8
  - binutils_linux-64=2.33.1=h9595d00_16
  - bioconductor-gem=1.12.0=r36_0
  - bwidget=1.9.14=0
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - curl=7.65.3=hf8cf82a_0
  - datamash=1.1.0=0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - fribidi=1.0.5=h516909a_1002
  - gcc_impl_linux-64=7.3.0=hd420e75_5
  - gcc_linux-64=7.3.0=h553295d_16
  - gettext=0.19.8.1=hc5be6a0_1002
  - gfortran_impl_linux-64=7.3.0=hdf63c60_5
  - gfortran_linux-64=7.3.0=h553295d_16
  - glib=2.58.3=h6f030ca_1002
  - graphite2=1.3.13=hf484d3e_1000
  - gsl=2.5=h294904e_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_5
  - gxx_linux-64=7.3.0=h553295d_16
  - harfbuzz=2.4.0=h9f30f68_3
  - htslib=1.9=h4da6232_3
  - icu=64.2=he1b5a44_1
  - jpeg=9c=h14c3975_1001
  - krb5=1.16.4=h2fd8d38_0
  - ld_impl_linux-64=2.33.1=h53a641e_8
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcurl=7.65.3=hda55be3_0
  - libdeflate=1.2=h516909a_1
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.8.3=he1b5a44_1001
  - make=4.2.1=h14c3975_2004
  - moreutils=0.5.7=1
  - ncurses=6.1=hf484d3e_1002
  - openssl=1.1.1d=h516909a_0
  - pango=1.42.4=ha030887_1
  - parallel=20200122=0
  - pcre=8.43=he1b5a44_0
  - perl=5.26.2=h516909a_1006
  - perl-vcftools-vcf=0.1.16=pl526_2
  - pixman=0.38.0=h516909a_1003
  - pthread-stubs=0.4=h14c3975_1001
  - r-askpass=1.1=r36hcdcec82_1
  - r-assertthat=0.2.1=r36h6115d3f_1
  - r-backports=1.1.5=r36hcdcec82_0
  - r-base=3.6.2=h3a67422_0
  - r-bh=1.69.0_1=r36h6115d3f_0
  - r-brew=1.0_6=r36h6115d3f_1002
  - r-callr=3.4.1=r36h6115d3f_0
  - r-cli=2.0.1=r36h6115d3f_0
  - r-clipr=0.7.0=r36h6115d3f_0
  - r-clisymbols=1.2.0=r36h6115d3f_1002
  - r-colorspace=1.4_1=r36hcdcec82_1
  - r-commonmark=1.7=r36hcdcec82_1001
  - r-covr=3.4.0=r36h0357c0b_0
  - r-crayon=1.3.4=r36h6115d3f_1002
  - r-crosstalk=1.0.0=r36h6115d3f_1002
  - r-curl=4.3=r36hcdcec82_0
  - r-desc=1.2.0=r36h6115d3f_1002
  - r-devtools=2.2.1=r36h6115d3f_0
  - r-digest=0.6.23=r36h0357c0b_0
  - r-dplyr=0.8.0.1=r36h29659fb_0
  - r-dt=0.12=r36h6115d3f_0
  - r-ellipsis=0.3.0=r36hcdcec82_0
  - r-evaluate=0.14=r36h6115d3f_1
  - r-fansi=0.4.1=r36hcdcec82_0
  - r-farver=2.0.3=r36h0357c0b_0
  - r-fastmap=1.0.1=r36h0357c0b_0
  - r-fs=1.3.1=r36h0357c0b_1
  - r-ggplot2=3.1.1=r36h6115d3f_0
  - r-ggrepel=0.8.1=r36h0357c0b_1
  - r-gh=1.1.0=r36h6115d3f_0
  - r-git2r=0.26.1=r36h5ca76e2_1
  - r-glue=1.3.1=r36hcdcec82_1
  - r-gtable=0.3.0=r36h6115d3f_2
  - r-hms=0.5.3=r36h6115d3f_0
  - r-htmltools=0.4.0=r36h0357c0b_0
  - r-htmlwidgets=1.5.1=r36h6115d3f_0
  - r-httpuv=1.5.2=r36h0357c0b_1
  - r-httr=1.4.1=r36h6115d3f_1
  - r-ini=0.3.1=r36h6115d3f_1002
  - r-jsonlite=1.6.1=r36hcdcec82_0
  - r-labeling=0.3=r36h6115d3f_1002
  - r-later=1.0.0=r36h0357c0b_0
  - r-lattice=0.20_38=r36hcdcec82_1002
  - r-lazyeval=0.2.2=r36hcdcec82_1
  - r-lifecycle=0.1.0=r36h6115d3f_0
  - r-magrittr=1.5=r36h6115d3f_1002
  - r-mass=7.3_51.5=r36hcdcec82_0
  - r-matrix=1.2_18=r36hcdcec82_0
  - r-memoise=1.1.0=r36h6115d3f_1003
  - r-mgcv=1.8_31=r36hcdcec82_0
  - r-mime=0.9=r36hcdcec82_0
  - r-munsell=0.5.0=r36h6115d3f_1002
  - r-nlme=3.1_143=r36h9bbef5b_0
  - r-openssl=1.4.1=r36h9c8475f_0
  - r-pillar=1.4.3=r36h6115d3f_0
  - r-pkgbuild=1.0.6=r36h6115d3f_0
  - r-pkgconfig=2.0.3=r36h6115d3f_0
  - r-pkgload=1.0.2=r36h0357c0b_1001
  - r-plogr=0.2.0=r36h6115d3f_0
  - r-plyr=1.8.5=r36h0357c0b_0
  - r-praise=1.0.0=r36h6115d3f_1003
  - r-prettyunits=1.1.1=r36h6115d3f_0
  - r-processx=3.4.1=r36hcdcec82_0
  - r-promises=1.1.0=r36h0357c0b_0
  - r-ps=1.3.0=r36hcdcec82_1001
  - r-purrr=0.3.3=r36hcdcec82_0
  - r-r6=2.4.1=r36h6115d3f_0
  - r-rcmdcheck=1.3.3=r36h6115d3f_2
  - r-rcolorbrewer=1.1_2=r36h6115d3f_0
  - r-rcpp=1.0.3=r36h0357c0b_0
  - r-readr=1.3.1=r36h0357c0b_1002
  - r-remotes=2.1.0=r36h6115d3f_1
  - r-reshape2=1.4.3=r36h0357c0b_1004
  - r-rex=1.1.2=r36h6115d3f_1001
  - r-rlang=0.4.4=r36hcdcec82_0
  - r-roxygen2=7.0.2=r36h0357c0b_0
  - r-rprojroot=1.3_2=r36h6115d3f_1002
  - r-rstudioapi=0.10=r36h6115d3f_2
  - r-rversions=2.0.1=r36h6115d3f_0
  - r-scales=1.1.0=r36h6115d3f_0
  - r-sessioninfo=1.1.1=r36h6115d3f_1001
  - r-shiny=1.4.0=r36h6115d3f_0
  - r-sourcetools=0.1.7=r36he1b5a44_1001
  - r-stringi=1.4.5=r36h0e574ca_0
  - r-stringr=1.4.0=r36h6115d3f_1
  - r-sys=3.3=r36hcdcec82_0
  - r-testthat=2.3.1=r36h0357c0b_0
  - r-tibble=2.1.3=r36hcdcec82_1
  - r-tidyselect=0.2.5=r36h29659fb_0
  - r-usethis=1.5.1=r36h6115d3f_1
  - r-utf8=1.1.4=r36hcdcec82_1001
  - r-vctrs=0.2.2=r36hcdcec82_0
  - r-viridislite=0.3.0=r36h6115d3f_1002
  - r-whisker=0.4=r36h6115d3f_0
  - r-withr=2.1.2=r36h6115d3f_1001
  - r-xml2=1.2.2=r36h0357c0b_0
  - r-xopen=1.0.0=r36h6115d3f_1002
  - r-xtable=1.8_4=r36h6115d3f_2
  - r-yaml=2.2.1=r36hcdcec82_0
  - r-zeallot=0.1.0=r36h6115d3f_1001
  - readline=8.0=hf8c457e_0
  - sed=4.7=h1bed415_1000
  - tabix=0.2.6=ha92aebf_0
  - tk=8.6.10=hed695b0_0
  - tktable=2.10=h555a92e_3
  - vcftools=0.1.16=he860b03_3
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
