name: ewas
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _r-mutex=1.0.1=anacondar_1
  - bcftools=1.9=ha228f0b_4
  - bedtools=2.29.2=hc088bd4_0
  - binutils_impl_linux-64=2.35.1=h17ad2fc_0
  - binutils_linux-64=2.35=hc3fd857_29
  - bioconductor-gem=1.16.0=r40_0
  - bwidget=1.9.14=ha770c72_0
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.11.0=h470a237_1
  - ca-certificates=2020.11.8=ha878542_0
  - cairo=1.16.0=h9f066cc_1006
  - certifi=2020.11.8=py39hf3d152e_0
  - curl=7.71.1=he644dc0_8
  - datamash=1.1.0=0
  - fontconfig=2.13.1=h7e3eb15_1002
  - freetype=2.10.4=h7ca028e_0
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=9.3.0=h28f5a38_17
  - gcc_linux-64=9.3.0=h7247604_29
  - gettext=0.19.8.1=hf34092f_1004
  - gfortran_impl_linux-64=9.3.0=h2bb4189_17
  - gfortran_linux-64=9.3.0=ha1c937c_29
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.6=hf94e986_0
  - gxx_impl_linux-64=9.3.0=h53cdd4c_17
  - gxx_linux-64=9.3.0=h0d07fa4_29
  - harfbuzz=2.7.2=ha5b49bf_1
  - icu=67.1=he1b5a44_0
  - jpeg=9d=h36c2ea0_0
  - kernel-headers_linux-64=2.6.32=h77966d4_13
  - krb5=1.17.1=hfafb76e_3
  - ld_impl_linux-64=2.35.1=hed1e6ac_0
  - libblas=3.9.0=2_openblas
  - libcblas=3.9.0=2_openblas
  - libcurl=7.71.1=hcdd3856_8
  - libdeflate=1.0=h14c3975_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-devel_linux-64=9.3.0=hfd08b2a_17
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgfortran-ng=9.3.0=he4bcb1c_17
  - libgfortran5=9.3.0=he4bcb1c_17
  - libglib=2.66.2=hbe7bbb4_0
  - libgomp=9.3.0=h5dbcf3e_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=2_openblas
  - libnghttp2=1.41.0=hab1572f_1
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libpng=1.6.37=h21135ba_2
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-devel_linux-64=9.3.0=h4084dd6_17
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - libtiff=4.1.0=h4f3a223_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h36c2ea0_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=h68273f3_2
  - lz4-c=1.9.2=he1b5a44_3
  - make=4.3=hd18ef5c_1
  - ncurses=6.2=h58526e2_4
  - numpy=1.19.4=py39h57d35e7_1
  - openssl=1.1.1h=h516909a_0
  - pango=1.42.4=h80147aa_5
  - pcre=8.44=he1b5a44_0
  - pcre2=10.35=h279444b_1
  - pip=20.2.4=py_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h14c3975_1001
  - python=3.9.0=h2a148a8_4_cpython
  - python_abi=3.9=1_cp39
  - r-argparse=2.0.3=r40h142f84f_0
  - r-askpass=1.1=r40hcdcec82_2
  - r-assertthat=0.2.1=r40h6115d3f_2
  - r-backports=1.2.0=r40h9e2df91_0
  - r-base=4.0.3=hc603457_2
  - r-base64enc=0.1_3=r40hcdcec82_1004
  - r-brio=1.1.0=r40h9e2df91_1
  - r-callr=3.5.1=r40h142f84f_0
  - r-cli=2.1.0=r40h142f84f_0
  - r-clipr=0.7.1=r40h142f84f_0
  - r-colorspace=2.0_0=r40h9e2df91_0
  - r-cpp11=0.2.4=r40hc72bb7e_0
  - r-crayon=1.3.4=r40h6115d3f_1003
  - r-crosstalk=1.1.0.1=r40h6115d3f_1
  - r-curl=4.3=r40hcdcec82_1
  - r-data.table=1.13.2=r40h0eb13af_0
  - r-desc=1.2.0=r40h6115d3f_1003
  - r-diffobj=0.3.2=r40h9e2df91_1
  - r-digest=0.6.27=r40h1b71b39_0
  - r-dplyr=1.0.2=r40h0357c0b_0
  - r-ellipsis=0.3.1=r40hcdcec82_0
  - r-evaluate=0.14=r40h6115d3f_2
  - r-fansi=0.4.1=r40hcdcec82_1
  - r-farver=2.0.3=r40h0357c0b_1
  - r-findpython=1.0.5=r40h6115d3f_2
  - r-generics=0.1.0=r40hc72bb7e_0
  - r-getopt=1.20.3=r40_2
  - r-ggplot2=3.3.2=r40h6115d3f_0
  - r-ggrepel=0.8.2=r40h0357c0b_1
  - r-glue=1.4.2=r40hcdcec82_0
  - r-gtable=0.3.0=r40h6115d3f_3
  - r-hexbin=1.28.1=r40h580db52_2
  - r-hms=0.5.3=r40h6115d3f_1
  - r-htmltools=0.5.0=r40h0357c0b_0
  - r-htmlwidgets=1.5.2=r40h142f84f_0
  - r-httr=1.4.2=r40h6115d3f_0
  - r-isoband=0.2.2=r40h0357c0b_0
  - r-jsonlite=1.7.1=r40hcdcec82_0
  - r-labeling=0.4.2=r40h142f84f_0
  - r-later=1.1.0.1=r40h0357c0b_0
  - r-lattice=0.20_41=r40hcdcec82_2
  - r-lazyeval=0.2.2=r40hcdcec82_2
  - r-lifecycle=0.2.0=r40h6115d3f_1
  - r-magrittr=1.5=r40h6115d3f_1003
  - r-mass=7.3_53=r40hcdcec82_0
  - r-matrix=1.2_18=r40h7fa42b6_3
  - r-mgcv=1.8_33=r40h7fa42b6_0
  - r-mime=0.9=r40hcdcec82_1
  - r-munsell=0.5.0=r40h6115d3f_1003
  - r-nlme=3.1_150=r40h580db52_0
  - r-openssl=1.4.3=r40he5c4762_0
  - r-pillar=1.4.6=r40h6115d3f_0
  - r-pkgbuild=1.1.0=r40h6115d3f_0
  - r-pkgconfig=2.0.3=r40h6115d3f_1
  - r-pkgload=1.1.0=r40h0357c0b_0
  - r-plotly=4.9.2.1=r40h6115d3f_1
  - r-praise=1.0.0=r40h6115d3f_1004
  - r-prettyunits=1.1.1=r40h6115d3f_1
  - r-processx=3.4.4=r40hcdcec82_0
  - r-promises=1.1.1=r40h0357c0b_0
  - r-ps=1.4.0=r40h0eb13af_0
  - r-purrr=0.3.4=r40hcdcec82_1
  - r-r6=2.5.0=r40hc72bb7e_0
  - r-rcolorbrewer=1.1_2=r40h6115d3f_1003
  - r-rcpp=1.0.5=r40he524a50_0
  - r-readr=1.4.0=r40h1b71b39_0
  - r-rematch2=2.1.2=r40h6115d3f_1
  - r-rlang=0.4.8=r40h9e2df91_0
  - r-rprojroot=2.0.2=r40hc72bb7e_0
  - r-rstudioapi=0.13=r40hc72bb7e_0
  - r-scales=1.1.1=r40h6115d3f_0
  - r-sys=3.4=r40hcdcec82_0
  - r-testthat=3.0.0=r40he524a50_0
  - r-tibble=3.0.4=r40h0eb13af_0
  - r-tidyr=1.1.2=r40h0357c0b_0
  - r-tidyselect=1.1.0=r40h6115d3f_0
  - r-utf8=1.1.4=r40hcdcec82_1003
  - r-vctrs=0.3.4=r40hcdcec82_0
  - r-viridislite=0.3.0=r40h6115d3f_1003
  - r-waldo=0.2.3=r40hc72bb7e_0
  - r-withr=2.3.0=r40h6115d3f_0
  - r-yaml=2.2.1=r40hcdcec82_1
  - r-zeallot=0.1.0=r40h6115d3f_1002
  - r-zip=2.1.1=r40hcdcec82_0
  - readline=8.0=he28a2e2_2
  - sed=4.8=he412f7d_0
  - setuptools=49.6.0=py39h079e4ff_2
  - sqlite=3.33.0=h4cf870e_1
  - sysroot_linux-64=2.12=h77966d4_13
  - tk=8.6.10=hed695b0_1
  - tktable=2.10=hb7b940f_3
  - tzdata=2020d=h516909a_0
  - vcftools=0.1.16=he513fc3_4
  - wheel=0.35.1=pyh9f0ad1d_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.5=h6597ccf_2
