name: ewas
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _r-mutex=1.0.1=anacondar_1
  - bcftools=1.10.2=h4f4756c_3
  - bedtools=2.29.2=hc088bd4_0
  - binutils_impl_linux-64=2.34=h2122c62_9
  - binutils_linux-64=2.34=h47ac705_27
  - bioconductor-gem=1.14.0=r40_0
  - bwidget=1.9.14=0
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=h3fc0475_1005
  - certifi=2020.6.20=py38h32f6830_0
  - curl=7.71.1=he644dc0_5
  - datamash=1.7=h516909a_0
  - fontconfig=2.13.1=h1056068_1002
  - freetype=2.10.2=he06d7ca_0
  - fribidi=1.0.10=h516909a_0
  - gcc_impl_linux-64=7.5.0=hda68d29_13
  - gcc_linux-64=7.5.0=hf34d7eb_27
  - gettext=0.19.8.1=hc5be6a0_1002
  - gfortran_impl_linux-64=7.5.0=h1104b78_16
  - gfortran_linux-64=7.5.0=ha781d05_27
  - glib=2.66.0=h0dae87d_0
  - graphite2=1.3.13=he1b5a44_1001
  - gsl=2.6=h294904e_0
  - gxx_impl_linux-64=7.5.0=h64c220c_13
  - gxx_linux-64=7.5.0=ha781d05_27
  - harfbuzz=2.7.2=hee91db6_0
  - htslib=1.10.2=hd3b49d5_1
  - icu=67.1=he1b5a44_0
  - jpeg=9d=h516909a_0
  - kernel-headers_linux-64=2.6.32=h77966d4_13
  - krb5=1.17.1=hfafb76e_3
  - ld_impl_linux-64=2.34=hc38a660_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libcurl=7.71.1=hcdd3856_5
  - libdeflate=1.6=h516909a_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h24d8f2e_16
  - libgfortran-ng=7.5.0=hdf63c60_16
  - libgomp=9.3.0=h24d8f2e_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.8.0=17_openblas
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libpng=1.6.37=hed695b0_2
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=hdf63c60_16
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=h68273f3_2
  - lz4-c=1.9.2=he1b5a44_3
  - make=4.3=h516909a_0
  - ncurses=6.2=he1b5a44_1
  - numpy=1.19.1=py38hbc27379_2
  - openssl=1.1.1g=h516909a_1
  - pango=1.42.4=h7062337_4
  - pcre=8.44=he1b5a44_0
  - pcre2=10.35=h2f06484_0
  - perl=5.30.3=h516909a_1
  - pip=20.2.3=py_0
  - pixman=0.38.0=h516909a_1003
  - pthread-stubs=0.4=h14c3975_1001
  - python=3.8.5=h1103e12_7_cpython
  - python_abi=3.8=1_cp38
  - r-argparse=2.0.1=r40h6115d3f_2
  - r-askpass=1.1=r40hcdcec82_2
  - r-assertthat=0.2.1=r40h6115d3f_2
  - r-backports=1.1.9=r40hcdcec82_0
  - r-base=4.0.2=he766273_1
  - r-base64enc=0.1_3=r40hcdcec82_1004
  - r-callr=3.4.4=r40h6115d3f_0
  - r-cli=2.0.2=r40h6115d3f_1
  - r-clipr=0.7.0=r40h6115d3f_1
  - r-colorspace=1.4_1=r40hcdcec82_2
  - r-crayon=1.3.4=r40h6115d3f_1003
  - r-crosstalk=1.1.0.1=r40h6115d3f_1
  - r-curl=4.3=r40hcdcec82_1
  - r-data.table=1.12.8=r40hcdcec82_1
  - r-desc=1.2.0=r40h6115d3f_1003
  - r-digest=0.6.25=r40h0357c0b_2
  - r-dplyr=1.0.2=r40h0357c0b_0
  - r-ellipsis=0.3.1=r40hcdcec82_0
  - r-evaluate=0.14=r40h6115d3f_2
  - r-fansi=0.4.1=r40hcdcec82_1
  - r-farver=2.0.3=r40h0357c0b_1
  - r-findpython=1.0.5=r40h6115d3f_2
  - r-generics=0.0.2=r40h6115d3f_1003
  - r-getopt=1.20.3=r40_2
  - r-ggplot2=3.3.2=r40h6115d3f_0
  - r-ggrepel=0.8.2=r40h0357c0b_1
  - r-glue=1.4.2=r40hcdcec82_0
  - r-gtable=0.3.0=r40h6115d3f_3
  - r-hexbin=1.28.1=r40h9bbef5b_1
  - r-hms=0.5.3=r40h6115d3f_1
  - r-htmltools=0.5.0=r40h0357c0b_0
  - r-htmlwidgets=1.5.1=r40h6115d3f_1
  - r-httr=1.4.2=r40h6115d3f_0
  - r-isoband=0.2.2=r40h0357c0b_0
  - r-jsonlite=1.7.1=r40hcdcec82_0
  - r-labeling=0.3=r40h6115d3f_1003
  - r-later=1.1.0.1=r40h0357c0b_0
  - r-lattice=0.20_41=r40hcdcec82_2
  - r-lazyeval=0.2.2=r40hcdcec82_2
  - r-lifecycle=0.2.0=r40h6115d3f_1
  - r-magrittr=1.5=r40h6115d3f_1003
  - r-mass=7.3_53=r40hcdcec82_0
  - r-matrix=1.2_18=r40h7fa42b6_3
  - r-mgcv=1.8_33=r40h7fa42b6_0
  - r-mime=0.9=r40hcdcec82_1
  - r-munsell=0.5.0=r40h6115d3f_1003
  - r-nlme=3.1_149=r40h9bbef5b_0
  - r-openssl=1.4.2=r40he5c4762_0
  - r-pillar=1.4.6=r40h6115d3f_0
  - r-pkgbuild=1.1.0=r40h6115d3f_0
  - r-pkgconfig=2.0.3=r40h6115d3f_1
  - r-pkgload=1.1.0=r40h0357c0b_0
  - r-plotly=4.9.2.1=r40h6115d3f_1
  - r-praise=1.0.0=r40h6115d3f_1004
  - r-prettyunits=1.1.1=r40h6115d3f_1
  - r-processx=3.4.4=r40hcdcec82_0
  - r-promises=1.1.1=r40h0357c0b_0
  - r-ps=1.3.4=r40hcdcec82_0
  - r-purrr=0.3.4=r40hcdcec82_1
  - r-r6=2.4.1=r40h6115d3f_1
  - r-rcolorbrewer=1.1_2=r40h6115d3f_1003
  - r-rcpp=1.0.4.6=r40h0357c0b_1
  - r-readr=1.3.1=r40h0357c0b_1004
  - r-rlang=0.4.7=r40hcdcec82_0
  - r-rprojroot=1.3_2=r40h6115d3f_1003
  - r-rstudioapi=0.11=r40h6115d3f_1
  - r-scales=1.1.1=r40h6115d3f_0
  - r-sys=3.4=r40hcdcec82_0
  - r-testthat=2.3.2=r40h0357c0b_1
  - r-tibble=3.0.3=r40hcdcec82_0
  - r-tidyr=1.1.2=r40h0357c0b_0
  - r-tidyselect=1.1.0=r40h6115d3f_0
  - r-utf8=1.1.4=r40hcdcec82_1003
  - r-vctrs=0.3.4=r40hcdcec82_0
  - r-viridislite=0.3.0=r40h6115d3f_1003
  - r-withr=2.2.0=r40h6115d3f_1
  - r-yaml=2.2.1=r40hcdcec82_1
  - r-zeallot=0.1.0=r40h6115d3f_1002
  - r-zip=2.1.1=r40hcdcec82_0
  - readline=8.0=he28a2e2_2
  - sed=4.8=hbfbb72e_0
  - setuptools=49.6.0=py38h32f6830_0
  - sqlite=3.33.0=h4cf870e_0
  - sysroot_linux-64=2.12=h77966d4_13
  - tk=8.6.10=hed695b0_0
  - tktable=2.10=h555a92e_3
  - vcftools=0.1.16=he513fc3_4
  - wheel=0.35.1=pyh9f0ad1d_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1009
  - zstd=1.4.5=h6597ccf_2
